name: Release

on:
  push:
    tags:
      - 'version/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install npm dependencies
        run: npm install -g vsce

      - name: Build package
        run: vsce package

      - name: Get release name
        id: vars
        run: echo "RELEASE_NAME=Version ${GITHUB_REF#refs/tags/version/}" >> $GITHUB_ENV

      - name: Extract latest changelog
        run: awk '/## \[/{if (x) {exit}; {x=1}; next} /^-/ {if (NR > 1) {print}}' CHANGELOG.md > release_body_file.txt

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: 'release_body_file.txt'
          files: '*.vsix'
          name: ${{ env.RELEASE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
